### ISSUE TITLE
[Bug] Invalid check passed to ImplicitImports in pre-commit

### ISSUE THREAD

**Issue by tmigot** [JuliaBesties/BestieTemplate.jl#527]
### Description

I got the following error when applying BestieTemplate to a new package and then running the pre-commit.

### Package Version

0.14.1

### Julia Version

1.11

### Reproduction steps

Run explicit import check in the precommit with the option `exclude_all_qualified_accesses_are_public`
```
  - repo: https://github.com/ericphanson/ExplicitImports.jl
    rev: v1.10.1
    hooks:
      - id: explicit-imports
        name: ExplicitImports checks
        args: [--print, --checklist, "exclude_all_qualified_accesses_are_public"]
```
following https://ericphanson.github.io/ExplicitImports.jl/stable/.

### Relevant log output

```shell
ExplicitImports checks...................................................Failed
- hook id: explicit-imports
- exit code: 1

ERROR: Invalid check passed to --checklist: exclude_all_qualified_access_are_public See the output of `--help` for usage details.
```

### Operating System

Windows

**Comment by abelsiqueira** [comment]
Hi @tmigot, thanks for reporting. Does it work vai ExplicitImports.jl directly?

**Comment by abelsiqueira** [comment]
Which version of the package you have installed?

**Comment by tmigot** [comment]
```
(@v1.11) pkg> st
Status `C:\Users\tangi\.julia\environments\v1.11\Project.toml`
  [e5d671a7] BestieTemplate v0.15.0
  [35a29f4d] DocumenterTools v0.1.20
  [7d51a73a] ExplicitImports v1.11.2
  [98e50ef6] JuliaFormatter v2.1.1
```

**Comment by tmigot** [comment]
Calling it this way: `ExplicitImports.main(["--print", "--checklist", "exclude_all_qualified_accesses_are_public"])` works, but not with the precommit.
The documentation of version 1.11 seems to indicate as well that the `"` is needed in the `..pre-commit-config.yaml` file ( https://juliatesting.github.io/ExplicitImports.jl/v1.11/ )
```
- repo: https://github.com/ericphanson/ExplicitImports.jl
  rev: v1.10.0
  hooks:
    - id: explicit-imports
      args: [--print,--checklist,"exclude_all_qualified_accesses_are_public"]
```
